name: rollerblading-website

services:
  # databases
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks: [rollerblading-net]

  events-db:
    image: postgres:16-alpine
    container_name: events-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${EVENTS_DB_USER}
      POSTGRES_PASSWORD: ${EVENTS_DB_PASSWORD}
      POSTGRES_DB: ${EVENTS_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - events_db_data:/var/lib/postgresql/data
    networks: [rollerblading-net]

  store-db:
    image: postgres:16-alpine
    container_name: store-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${STORE_DB_USER}
      POSTGRES_PASSWORD: ${STORE_DB_PASSWORD}
      POSTGRES_DB: ${STORE_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - store_db_data:/var/lib/postgresql/data
    networks: [rollerblading-net]

  content-db:
    image: mongo:7
    container_name: content-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CONTENT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CONTENT_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${CONTENT_DB_NAME}
    ports:
      - "5436:27017"
    volumes:
      - content_db_data:/data/db
    networks: [rollerblading-net]

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ./backend/auth-service/.env
    environment:
      DATABASE_URL: postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    networks: [rollerblading-net]

networks:
  rollerblading-net:
    driver: bridge

volumes:
  auth_db_data:
  events_db_data:
  store_db_data:
  content_db_data: